In [7]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [8]:
df = pd.read_excel("Online retail.xlsx")
df.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [10]:
# Identify missing value
df.isnull().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

In [14]:
# Extract the first column (transactions)
# Your dataset likely has one column where each row = one transaction
transactions = df.iloc[:, 0].dropna().apply(lambda x: [item.strip() for item in str(x).split(',')])

In [15]:
transactions

0                              [burgers, meatballs, eggs]
1                                               [chutney]
2                                       [turkey, avocado]
3       [mineral water, milk, energy bar, whole wheat ...
4                                        [low fat yogurt]
                              ...
7495                    [butter, light mayo, fresh bread]
7496    [burgers, frozen vegetables, eggs, french frie...
7497                                            [chicken]
7498                                [escalope, green tea]
7499    [eggs, frozen smoothie, yogurt cake, low fat y...
Name: shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil, Length: 7500, dtype: object

In [16]:
#Use TransactionEncoder to convert into 1/0 (Boolean) format
te = TransactionEncoder()
enc_matrix = te.fit(transactions).transform(transactions)

In [17]:
te.columns_

['almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [18]:
encoded_df = pd.DataFrame(enc_matrix, columns=te.columns_)
encoded_df

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [21]:
#  Apply Apriori Algorithm
frequent_items = apriori(encoded_df, min_support=0.02, use_colnames=True)
frequent_items

      support                           itemsets
0    0.020267                          (almonds)
1    0.033200                          (avocado)
2    0.033733                         (brownies)
3    0.087200                          (burgers)
4    0.030133                           (butter)
..        ...                                ...
99   0.020133  (whole wheat rice, mineral water)
100  0.022933             (spaghetti, olive oil)
101  0.025200              (spaghetti, pancakes)
102  0.021200                (spaghetti, shrimp)
103  0.020933              (spaghetti, tomatoes)

[104 rows x 2 columns]

In [25]:
#  Generate Association Rules
rules = association_rules(frequent_items, metric="lift", min_threshold=1.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(burgers),(eggs),0.087200,0.179733,0.028800,0.330275,1.837585,1.0,0.013127,1.224782,0.499351,0.120941,0.183528,0.245256
1,(eggs),(burgers),0.179733,0.087200,0.028800,0.160237,1.837585,1.0,0.013127,1.086974,0.555682,0.120941,0.080015,0.245256
2,(mineral water),(chicken),0.238267,0.060000,0.022800,0.095691,1.594852,1.0,0.008504,1.039468,0.489650,0.082769,0.037969,0.237846
3,(chicken),(mineral water),0.060000,0.238267,0.022800,0.380000,1.594852,1.0,0.008504,1.228602,0.396790,0.082769,0.186067,0.237846
4,(chocolate),(milk),0.163867,0.129600,0.032133,0.196094,1.513074,1.0,0.010896,1.082714,0.405550,0.122959,0.076395,0.222018
5,(milk),(chocolate),0.129600,0.163867,0.032133,0.247942,1.513074,1.0,0.010896,1.111794,0.389584,0.122959,0.100553,0.222018
6,(mineral water),(cooking oil),0.238267,0.051067,0.020133,0.084499,1.654683,1.0,0.007966,1.036518,0.519414,0.074789,0.035232,0.239378
7,(cooking oil),(mineral water),0.051067,0.238267,0.020133,0.394256,1.654683,1.0,0.007966,1.257517,0.416947,0.074789,0.204782,0.239378
8,(frozen vegetables),(milk),0.095333,0.129600,0.023600,0.247552,1.910127,1.0,0.011245,1.156758,0.526685,0.117219,0.135515,0.214826
9,(milk),(frozen vegetables),0.129600,0.095333,0.023600,0.182099,1.910127,1.0,0.011245,1.106083,0.547420,0.117219,0.095909,0.214826
10,(frozen vegetables),(mineral water),0.095333,0.238267,0.035733,0.374825,1.573133,1.0,0.013019,1.218433,0.402718,0.119964,0.179273,0.262399
11,(mineral water),(frozen vegetables),0.238267,0.095333,0.035733,0.149972,1.573133,1.0,0.013019,1.064279,0.478285,0.119964,0.060396,0.262399
12,(spaghetti),(frozen vegetables),0.174133,0.095333,0.027867,0.160031,1.678643,1.0,0.011266,1.077023,0.489523,0.115342,0.071515,0.226169
13,(frozen vegetables),(spaghetti),0.095333,0.174133,0.027867,0.292308,1.678643,1.0,0.011266,1.166986,0.446884,0.115342,0.143091,0.226169
14,(ground beef),(milk),0.098267,0.129600,0.022000,0.223881,1.727474,1.0,0.009265,1.121477,0.467012,0.106865,0.108319,0.196817
15,(milk),(ground beef),0.129600,0.098267,0.022000,0.169753,1.727474,1.0,0.009265,1.086103,0.483824,0.106865,0.079277,0.196817
16,(ground beef),(mineral water),0.098267,0.238267,0.040933,0.416554,1.748266,1.0,0.017520,1.305576,0.474647,0.138475,0.234054,0.294175
17,(mineral water),(ground beef),0.238267,0.098267,0.040933,0.171796,1.748266,1.0,0.017520,1.088782,0.561883,0.138475,0.081543,0.294175
18,(ground beef),(spaghetti),0.098267,0.174133,0.039200,0.398915,2.290857,1.0,0.022088,1.373959,0.624888,0.168096,0.272176,0.312015
19,(spaghetti),(ground beef),0.174133,0.098267,0.039200,0.225115,2.290857,1.0,0.022088,1.163699,0.682292,0.168096,0.140672,0.312015
20,(milk),(mineral water),0.129600,0.238267,0.048000,0.370370,1.554436,1.0,0.017121,1.209812,0.409789,0.150063,0.173425,0.285913
21,(mineral water),(milk),0.238267,0.129600,0.048000,0.201455,1.554436,1.0,0.017121,1.089982,0.468248,0.150063,0.082554,0.285913
22,(spaghetti),(milk),0.174133,0.129600,0.035467,0.203675,1.571569,1.0,0.012899,1.093022,0.440378,0.132207,0.085105,0.238669
23,(milk),(spaghetti),0.129600,0.174133,0.035467,0.273663,1.571569,1.0,0.012899,1.137029,0.417846,0.132207,0.120515,0.238669
24,(olive oil),(mineral water),0.065733,0.238267,0.027467,0.417850,1.753707,1.0,0.011805,1.308483,0.460018,0.099325,0.235756,0.266563
25,(mineral water),(olive oil),0.238267,0.065733,0.027467,0.115277,1.753707,1.0,0.011805,1.055999,0.564212,0.099325,0.053029,0.266563
26,(soup),(mineral water),0.050533,0.238267,0.023067,0.456464,1.915771,1.0,0.011026,1.401441,0.503458,0.086804,0.286449,0.276637
27,(mineral water),(soup),0.238267,0.050533,0.023067,0.096810,1.915771,1.0,0.011026,1.051237,0.627538,0.086804,0.048740,0.276637
28,(spaghetti),(olive oil),0.174133,0.065733,0.022933,0.131700,2.003547,1.0,0.011487,1.075972,0.606497,0.105716,0.070608,0.240292
29,(olive oil),(spaghetti),0.065733,0.174133,0.022933,0.348884,2.003547,1.0,0.011487,1.268387,0.536127,0.105716,0.211597,0.240292
30,(spaghetti),(pancakes),0.174133,0.095067,0.025200,0.144717,1.522265,1.0,0.008646,1.058051,0.415423,0.103279,0.054866,0.204897
31,(pancakes),(spaghetti),0.095067,0.174133,0.025200,0.265077,1.522265,1.0,0.008646,1.123746,0.379127,0.103279,0.110119,0.204897
32,(spaghetti),(shrimp),0.174133,0.071333,0.021200,0.121746,1.706717,1.0,0.008778,1.057401,0.501388,0.094530,0.054285,0.209471
33,(shrimp),(spaghetti),0.071333,0.174133,0.021200,0.297196,1.706717,1.0,0.008778,1.175103,0.445886,0.094530,0.149011,0.209471
34,(spaghetti),(tomatoes),0.174133,0.068400,0.020933,0.120214,1.757520,1.0,0.009023,1.058894,0.521896,0.094465,0.055619,0.213129
35,(tomatoes),(spaghetti),0.068400,0.174133,0.020933,0.306043,1.757520,1.0,0.009023,1.190083,0.462663,0.094465,0.159723,0.213129

In [26]:
rules[rules['lift']>1.5]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(burgers),(eggs),0.087200,0.179733,0.028800,0.330275,1.837585,1.0,0.013127,1.224782,0.499351,0.120941,0.183528,0.245256
1,(eggs),(burgers),0.179733,0.087200,0.028800,0.160237,1.837585,1.0,0.013127,1.086974,0.555682,0.120941,0.080015,0.245256
2,(mineral water),(chicken),0.238267,0.060000,0.022800,0.095691,1.594852,1.0,0.008504,1.039468,0.489650,0.082769,0.037969,0.237846
3,(chicken),(mineral water),0.060000,0.238267,0.022800,0.380000,1.594852,1.0,0.008504,1.228602,0.396790,0.082769,0.186067,0.237846
4,(chocolate),(milk),0.163867,0.129600,0.032133,0.196094,1.513074,1.0,0.010896,1.082714,0.405550,0.122959,0.076395,0.222018
5,(milk),(chocolate),0.129600,0.163867,0.032133,0.247942,1.513074,1.0,0.010896,1.111794,0.389584,0.122959,0.100553,0.222018
6,(mineral water),(cooking oil),0.238267,0.051067,0.020133,0.084499,1.654683,1.0,0.007966,1.036518,0.519414,0.074789,0.035232,0.239378
7,(cooking oil),(mineral water),0.051067,0.238267,0.020133,0.394256,1.654683,1.0,0.007966,1.257517,0.416947,0.074789,0.204782,0.239378
8,(frozen vegetables),(milk),0.095333,0.129600,0.023600,0.247552,1.910127,1.0,0.011245,1.156758,0.526685,0.117219,0.135515,0.214826
9,(milk),(frozen vegetables),0.129600,0.095333,0.023600,0.182099,1.910127,1.0,0.011245,1.106083,0.547420,0.117219,0.095909,0.214826
10,(frozen vegetables),(mineral water),0.095333,0.238267,0.035733,0.374825,1.573133,1.0,0.013019,1.218433,0.402718,0.119964,0.179273,0.262399
11,(mineral water),(frozen vegetables),0.238267,0.095333,0.035733,0.149972,1.573133,1.0,0.013019,1.064279,0.478285,0.119964,0.060396,0.262399
12,(spaghetti),(frozen vegetables),0.174133,0.095333,0.027867,0.160031,1.678643,1.0,0.011266,1.077023,0.489523,0.115342,0.071515,0.226169
13,(frozen vegetables),(spaghetti),0.095333,0.174133,0.027867,0.292308,1.678643,1.0,0.011266,1.166986,0.446884,0.115342,0.143091,0.226169
14,(ground beef),(milk),0.098267,0.129600,0.022000,0.223881,1.727474,1.0,0.009265,1.121477,0.467012,0.106865,0.108319,0.196817
15,(milk),(ground beef),0.129600,0.098267,0.022000,0.169753,1.727474,1.0,0.009265,1.086103,0.483824,0.106865,0.079277,0.196817
16,(ground beef),(mineral water),0.098267,0.238267,0.040933,0.416554,1.748266,1.0,0.017520,1.305576,0.474647,0.138475,0.234054,0.294175
17,(mineral water),(ground beef),0.238267,0.098267,0.040933,0.171796,1.748266,1.0,0.017520,1.088782,0.561883,0.138475,0.081543,0.294175
18,(ground beef),(spaghetti),0.098267,0.174133,0.039200,0.398915,2.290857,1.0,0.022088,1.373959,0.624888,0.168096,0.272176,0.312015
19,(spaghetti),(ground beef),0.174133,0.098267,0.039200,0.225115,2.290857,1.0,0.022088,1.163699,0.682292,0.168096,0.140672,0.312015
20,(milk),(mineral water),0.129600,0.238267,0.048000,0.370370,1.554436,1.0,0.017121,1.209812,0.409789,0.150063,0.173425,0.285913
21,(mineral water),(milk),0.238267,0.129600,0.048000,0.201455,1.554436,1.0,0.017121,1.089982,0.468248,0.150063,0.082554,0.285913
22,(spaghetti),(milk),0.174133,0.129600,0.035467,0.203675,1.571569,1.0,0.012899,1.093022,0.440378,0.132207,0.085105,0.238669
23,(milk),(spaghetti),0.129600,0.174133,0.035467,0.273663,1.571569,1.0,0.012899,1.137029,0.417846,0.132207,0.120515,0.238669
24,(olive oil),(mineral water),0.065733,0.238267,0.027467,0.417850,1.753707,1.0,0.011805,1.308483,0.460018,0.099325,0.235756,0.266563
25,(mineral water),(olive oil),0.238267,0.065733,0.027467,0.115277,1.753707,1.0,0.011805,1.055999,0.564212,0.099325,0.053029,0.266563
26,(soup),(mineral water),0.050533,0.238267,0.023067,0.456464,1.915771,1.0,0.011026,1.401441,0.503458,0.086804,0.286449,0.276637
27,(mineral water),(soup),0.238267,0.050533,0.023067,0.096810,1.915771,1.0,0.011026,1.051237,0.627538,0.086804,0.048740,0.276637
28,(spaghetti),(olive oil),0.174133,0.065733,0.022933,0.131700,2.003547,1.0,0.011487,1.075972,0.606497,0.105716,0.070608,0.240292
29,(olive oil),(spaghetti),0.065733,0.174133,0.022933,0.348884,2.003547,1.0,0.011487,1.268387,0.536127,0.105716,0.211597,0.240292
30,(spaghetti),(pancakes),0.174133,0.095067,0.025200,0.144717,1.522265,1.0,0.008646,1.058051,0.415423,0.103279,0.054866,0.204897
31,(pancakes),(spaghetti),0.095067,0.174133,0.025200,0.265077,1.522265,1.0,0.008646,1.123746,0.379127,0.103279,0.110119,0.204897
32,(spaghetti),(shrimp),0.174133,0.071333,0.021200,0.121746,1.706717,1.0,0.008778,1.057401,0.501388,0.094530,0.054285,0.209471
33,(shrimp),(spaghetti),0.071333,0.174133,0.021200,0.297196,1.706717,1.0,0.008778,1.175103,0.445886,0.094530,0.149011,0.209471
34,(spaghetti),(tomatoes),0.174133,0.068400,0.020933,0.120214,1.757520,1.0,0.009023,1.058894,0.521896,0.094465,0.055619,0.213129
35,(tomatoes),(spaghetti),0.068400,0.174133,0.020933,0.306043,1.757520,1.0,0.009023,1.190083,0.462663,0.094465,0.159723,0.213129

#### Analysis and Interpretation:

###### From the generated association rules, it is observed that products like **mineral water, spaghetti, milk, and ground beef** frequently appear together, indicating strong purchasing relationships. Rules with higher **lift values (above 1.5)** and moderate **support (above 0.02)** suggest meaningful associations — for example, customers who buy spaghetti are about **2.3 times more likely** to buy ground beef. Such insights can help in **cross-selling strategies**, optimizing **store layouts**, and improving **inventory management** by ensuring complementary products are stocked together. Overall, association rule mining provides valuable understanding of **customer buying patterns**, enabling data-driven marketing and sales decisions.

#### Lift and its Importance:

###### Lift measures how much more likely two items are to be bought together compared to being bought independently. It is calculated as the ratio of the observed support to the expected support if the items were independent. A lift value greater than 1 indicates a positive association, meaning the items are frequently purchased together. It is important because it helps identify strong, non-random relationships between products, providing deeper insights than confidence alone.

#### Support and Confidence:

###### Support indicates how often a particular itemset appears in the dataset, showing the overall frequency of a rule. It is calculated as the number of transactions containing the itemset divided by the total number of transactions. Confidence measures the reliability of a rule, calculated as the ratio of the number of transactions containing both items (A and B) to the number containing only A. Together, they help evaluate the strength and significance of association rules.

#### Limitations of Association Rule Mining:

###### Some key challenges include generating a large number of irrelevant or redundant rules, especially in large datasets. Setting proper thresholds for support and confidence is difficult — too high may miss useful patterns, while too low may produce too many weak rules. Additionally, association rules only capture co-occurrence relationships and not causality, which can sometimes lead to misleading conclusions.